spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coffee_break
    username: pedro
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect