spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/coffee_break
    username: amigoscode
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8090